### ISSUE TITLE
Another parsing issue?

### ISSUE THREAD

**Issue by frenzy382** [vorghahn/iptv4plex#14]
Hi...
I keep getting the below  I create my m3u's and xml's from the online service of "EPG for ITPV".

2018-07-17 21:31:46,928 - INFO       - iptv4plex  -  <module>                 - Initializing
2018-07-17 21:31:46,928 - DEBUG      - iptv4plex  -  load_settings            - Parsing settings
2018-07-17 21:31:46,929 - DEBUG      - iptv4plex  -  load_settings            - Using config file.
2018-07-17 21:31:46,930 - INFO       - iptv4plex  -  <module>                 - Building initial playlist...
2018-07-17 21:31:47,716 - DEBUG      - iptv4plex  -  xmltv_merger             - Request was not redirected
2018-07-17 21:31:47,832 - ERROR      - iptv4plex  -  <module>                 - Exception while building initial playlist: 
Traceback (most recent call last):
  File "iptv4plex.py", line 899, in <module>
  File "iptv4plex.py", line 563, in obtain_epg
  File "iptv4plex.py", line 580, in xmltv_merger
  File "urllib\request.py", line 187, in urlretrieve
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by vorghahn** [comment]
I'm assuming that you need to log in to that service as that's what the error is implying, a failed or lack of a logon.
