### ISSUE TITLE
Error while parsing epg.xml

### ISSUE THREAD

**Issue by philiplawall** [vorghahn/iptv4plex#2]
Just tried using the windows version with an tv-mosaic.com server and I got the following error:

```
[2018-05-15 19:08:47,121] ERROR in app: Exception on /epg.xml [GET]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1982, in wsgi_app
  File "site-packages\flask\app.py", line 1614, in full_dispatch_request
  File "site-packages\flask\app.py", line 1517, in handle_user_exception
  File "site-packages\flask\_compat.py", line 33, in reraise
  File "site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "site-packages\flask\app.py", line 1598, in dispatch_request
  File "iptv4plex.py", line 771, in main_tuner
  File "iptv4plex.py", line 552, in obtain_epg
  File "iptv4plex.py", line 561, in xmltv_merger
  File "xml\etree\ElementTree.py", line 1183, in parse
  File "xml\etree\ElementTree.py", line 594, in parse
  File "<string>", line None
xml.etree.ElementTree.ParseError: duplicate attribute: line 10317, column 113
```

The Error only seems to be happening if Plex tries to grab the /epg.xml. When manually access the epg via Google Chrome the error doesn't happen.

Attached is the cached epg.xml and raw.xml as txt file
[epg.txt](https://github.com/vorghahn/iptv4plex/files/2005984/epg.txt)
[raw.txt](https://github.com/vorghahn/iptv4plex/files/2006000/raw.txt)

**Comment by vorghahn** [comment]
Did you try to add the same EPG url to the proxy more than once?

Both Plex and Chrome will access it the same way, however there is a 3hr cache in place for the EPG so that is why chrome did not see the issue.

To retest delete the epg.xml and raw.xml and it'll be forced to regather the data.

**Comment by vorghahn** [comment]
Issue should be resolved in v0.2, test it and report back please.

**Comment by philiplawall** [comment]
Thank you. The issue seems to be resolved now.
Unfortunaly Plex is currently not displaying any Channels and EPG Information. I'll open a new Issue if I find the source of this.

**Comment by philiplawall** [comment]
Well it seems that tv-mosaic.com is creating xmltv files which dont adhere to the standard used by Plex. (https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd) So Plex is unable to read the files. This is not an error with iptv4plux but with tv-mosaic. I contactet the support but havent heard back yet.
