### ISSUE TITLE
Archive Failed

### ISSUE THREAD

**Issue by justinglock40** [vorghahn/iptv4plex#3]
Can you get this to use m3u lists? My provider doesn't offer a m3u8.
They provide http://tv.tv/get.php?username=XXXX&password=XXXX&type=m3u_plus&output=ts
I tried putting it in, but the application returns archive failed on Windows

**Comment by justinglock40** [comment]
2018-05-15 17:40:36,834 - INFO       - iptv4plex  -  <module>                 - Initializing
2018-05-15 17:40:36,834 - DEBUG      - iptv4plex  -  load_settings            - No config file found.
2018-05-15 17:40:36,834 - DEBUG      - iptv4plex  -  load_settings            - Parsing settings
2018-05-15 17:41:59,576 - INFO       - iptv4plex  -  <module>                 - Building initial playlist...
2018-05-15 17:41:59,576 - DEBUG      - iptv4plex  -  m3u8_merger              - m3u8 url
2018-05-15 17:42:01,201 - ERROR      - iptv4plex  -  <module>                 - Exception while building initial playlist: 
Traceback (most recent call last):
  File "iptv4plex.py", line 875, in <module>
  File "iptv4plex.py", line 418, in build_channel_map
  File "iptv4plex.py", line 459, in obtain_m3u8
  File "iptv4plex.py", line 493, in m3u8_merger
IndexError: list index out of range

**Comment by vorghahn** [comment]
Try v0.12 and report back please.

**Comment by justinglock40** [comment]
is there an .exe available?

**Comment by vorghahn** [comment]
If this is resolved for you can you please close it?
