### ISSUE TITLE
Xtream-editor EPG not parsing

### ISSUE THREAD

**Issue by tenzone** [vorghahn/iptv4plex#7]
my IPTV is piped through xtream-editor to truncate and just make easier for use.  It seemed to not like the formatting.  the error is as follows:

```
Copy paste in xml URL, seperate multiple using ;http://xtream-editor.com/en/get/epg/03783BB3EADDFCF73051545FFF8E4BBD
2018-05-21 10:10:05,126 - INFO       - iptv4plex  -  <module>                 - Building initial playlist...
2018-05-21 10:10:05,435 - ERROR      - iptv4plex  -  <module>                 - Exception while building initial playlist:
Traceback (most recent call last):
  File "iptv4plex.py", line 884, in <module>
    obtain_epg()
  File "iptv4plex.py", line 561, in obtain_epg
    xmltv_merger(i)
  File "iptv4plex.py", line 576, in xmltv_merger
    source = ET.parse(opened)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

i was able to get it going using the epg i use to make my xtream editor code, but not without significant work. This might be a fringe case, but it could be helpful if it could parse this type of file.  if needed you can get the epg contents from `http://xtream-editor.com/en/get/epg/03783BB3EADDFCF73051545FFF8E4BBD`

**Comment by vorghahn** [comment]
Ok it's due to the file being gzipped but there's no indication in the url that says that it'll be zipped.

**Comment by vorghahn** [comment]
Are all xtreme-editor epg outputs in gzip?

**Comment by tenzone** [comment]
looks like it...   theres only one EPG option it seems. all the other items are m3u playlists for different devices
![screen shot 2018-05-24 at 7 43 59 am](https://user-images.githubusercontent.com/31738727/40483535-59740446-5f26-11e8-9393-522ef69dfe6a.png)

**Comment by vorghahn** [comment]
Try v0.22 and report back, close if it fixes it please.

**Comment by tenzone** [comment]
``` python3 iptv4plex.py        
2018-05-24 22:26:18,517 - INFO       - iptv4plex  -  <module>                 - Initializing
2018-05-24 22:26:18,542 - INFO       - iptv4plex  -  <module>                 - Building initial playlist...
2018-05-24 22:26:18,542 - ERROR      - iptv4plex  -  <module>                 - Exception while building initial playlist:
Traceback (most recent call last):
  File "iptv4plex.py", line 891, in <module>
    obtain_epg()
  File "iptv4plex.py", line 562, in obtain_epg
    xmltv_merger(i)
  File "iptv4plex.py", line 566, in xmltv_merger
    if xml_url.endswith('.gz') or xml_url.contains('xtream-editor.com'):
AttributeError: 'str' object has no attribute 'contains'```

**Comment by vorghahn** [comment]
Oh man I'm mixing syntax, gimme a second!

Try again now sorry.

**Comment by tenzone** [comment]
hmm . unfortunatley still not . heres the newest output:
```
python3 iptv4plex.py -hl          
2018-05-24 23:30:31,654 - INFO       - iptv4plex  -  <module>                 - Initializing
2018-05-24 23:30:31,678 - INFO       - iptv4plex  -  <module>                 - Building initial playlist...
2018-05-24 23:30:32,228 - ERROR      - iptv4plex  -  <module>                 - Exception while building initial playlist:
Traceback (most recent call last):
  File "iptv4plex.py", line 578, in xmltv_merger
    source = ET.parse(opened)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'{"')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "iptv4plex.py", line 891, in <module>
    obtain_epg()
  File "iptv4plex.py", line 562, in obtain_epg
    xmltv_merger(i)
  File "iptv4plex.py", line 583, in xmltv_merger
    source = ET.parse(opened)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'{"')
```


EDIT: btw, thanks for all the help, i know youre not getting paid for this..   once i get some disposable cash ill send to the donation box

**Comment by vorghahn** [comment]
Try again:
0.23 - Added epg redirection detection

I was able to test it this time and seemed to work.

**Comment by tenzone** [comment]
yes this time it works... thank man .  closing the issue
